create database GIAIDE_2
go

use database GIAIDE_2
go

CREATE DATABASE CSDL De02
GO
USE CSDL_De02
GO
--drop table SINHVIEN
CREATE TABLE SINHVIEN
 (      
 MASV VARCHAR(5) PRIMARY KEY,
 HOTENN	VARCHAR(50),
 NGAYSINH VARCHAR(20),
 GIOITINH BIT,
 DIENTHOAI VARCHAR(20),
 DIACHI NVARCHAR(50),
 MALOP VARCHAR(15)
 )