--MỞ CSDL MASTER

USE MASTER
GO
-- Xóa database
DROP DATABASE QUANLYKHOA
GO
-- Tạo database
CREATE DATABASE QUANLYKHOA
GO
--Mở CSDL QUANLYKHOA
GO
USE QUANLYKHOA
GO
-- 1. Tạo bảng KHOA
-- DROP TABLE KHOA
CREATE TABLE KHOA
(
		MAKHOA				VARCHAR(5) PRIMARY KEY,
		TENKHOA				NVARCHAR(50),
		TRUONGKHOA	NVARCHAR(50),
		DIENTHOAI			VARCHAR(15)
)
-- Nhập dữ liệu cho bảng KHOA
INSERT INTO KHOA(MAKHOA, TENKHOA, TRUONGKHOA, DIENTHOAI) 
VALUES('CNTT', N'Công nghệ thông tin', N'Đỗ Sính', '0905123123')

INSERT INTO KHOA(MAKHOA, TENKHOA, TRUONGKHOA, DIENTHOAI) 
VALUES('KT', N'Kế toán', N'Trương Văn Trí', '0905123124')

INSERT INTO KHOA(MAKHOA, TENKHOA, TRUONGKHOA, DIENTHOAI) 
VALUES('XD', N'Xây dựng', N'Lương Vĩnh Phú', '0905123124')


INSERT INTO KHOA(MAKHOA, TENKHOA, TRUONGKHOA, DIENTHOAI) 
VALUES('DIEN', N'Điện', N'Nguyễn Lê Hoàng', '0905123124')
-- hiển thị dữ liệu
SELECT * FROM KHOA
-- 2. Tạo bảng GIAOVIEN
CREATE TABLE GIAOVIEN
(
	MAGV					VARCHAR(5) PRIMARY KEY,
	HOTENGV				NVARCHAR(50),
	NGAYSINH			DATETIME,
	TRINHDO				NVARCHAR(50),
	DIENTHOAI			VARCHAR(15),
	DIACHI					NVARCHAR(100),
	NGAYLAMVIEC  DATETIME,
	MAKHOA				VARCHAR(5) FOREIGN KEY REFERENCES KHOA(MAKHOA)
)
GO
-- Nhập dữ liệu
insert into GIAOVIEN(MAGV, HOTENGV, NGAYSINH, TRINHDO, DIENTHOAI, DIACHI, NGAYLAMVIEC, MAKHOA)
values('GV001',N'Nguyễn Tuấn', '1988/08/09', N'Thạc sỹ', '0909123123', N'Đà Nẵng', '2021/11/16', 'CNTT')

insert into GIAOVIEN(MAGV, HOTENGV, NGAYSINH, TRINHDO, DIENTHOAI, DIACHI, NGAYLAMVIEC, MAKHOA)
values('GV002',N'Nguyễn Văn Cảnh', '1988/08/19', N'Thạc sỹ', '0909123124', N'Đà Nẵng', '2021/11/16', 'CNTT')
GO
-- hiển thị dữ liệu
select * from GIAOVIEN



